//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.SSIS.ControlFlow.Waiting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP.SSIS.ControlFlow.Waiting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor for {0}.
        /// </summary>
        internal static string EditorFor {
            get {
                return ResourceManager.GetString("EditorFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckIntaval has to be grater than 0.
        /// </summary>
        internal static string ErrorCheckInterval {
            get {
                return ResourceManager.GetString("ErrorCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize property &apos;{0}&apos;. Unknown value &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorCouldNotDeserializeProperty {
            get {
                return ResourceManager.GetString("ErrorCouldNotDeserializeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot lock Signal variable &apos;{0}&apos; for reading..
        /// </summary>
        internal static string ErrorLockSignalVariable {
            get {
                return ResourceManager.GetString("ErrorLockSignalVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misssing file to check..
        /// </summary>
        internal static string ErrorMissingFileToCheck {
            get {
                return ResourceManager.GetString("ErrorMissingFileToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilesToCheck is not a valid file name..
        /// </summary>
        internal static string ErrorNotValidFileToCheck {
            get {
                return ResourceManager.GetString("ErrorNotValidFileToCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal variable &apos;{0}&apos; does not exists..
        /// </summary>
        internal static string ErrorSignalVariableDoesNotExists {
            get {
                return ResourceManager.GetString("ErrorSignalVariableDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal variable has to be specified..
        /// </summary>
        internal static string ErrorSignalVariableHasToBeSpecified {
            get {
                return ResourceManager.GetString("ErrorSignalVariableHasToBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type of Signal variable &apos;{0}&apos; is not boolean..
        /// </summary>
        internal static string ErrorSignalVariableNotBoolean {
            get {
                return ResourceManager.GetString("ErrorSignalVariableNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal variable is not from [User] namespace. A Signal varaible has to be from within [User] namespace..
        /// </summary>
        internal static string ErrorSignalWariableNotFromUser {
            get {
                return ResourceManager.GetString("ErrorSignalWariableNotFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SleepInterval has to be greater than 0..
        /// </summary>
        internal static string ErrorSleepInterval {
            get {
                return ResourceManager.GetString("ErrorSleepInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitTime is not walid day time..
        /// </summary>
        internal static string ErrorWaitForTime {
            get {
                return ResourceManager.GetString("ErrorWaitForTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SleepTask.
        /// </summary>
        internal static string SleepTaskName {
            get {
                return ResourceManager.GetString("SleepTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Files|*.chk|Text Files|*.txt|CSV Files|*.csv|All Files|*.*.
        /// </summary>
        internal static string WaitForFileFilter {
            get {
                return ResourceManager.GetString("WaitForFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForFile.
        /// </summary>
        internal static string WaitForFileTaskName {
            get {
                return ResourceManager.GetString("WaitForFileTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForSignalTask.
        /// </summary>
        internal static string WaitForSignalTaskName {
            get {
                return ResourceManager.GetString("WaitForSignalTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForTime.
        /// </summary>
        internal static string WaitForTimeTaskName {
            get {
                return ResourceManager.GetString("WaitForTimeTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaitForFile.
        /// </summary>
        internal static string WatForFileTaskName {
            get {
                return ResourceManager.GetString("WatForFileTaskName", resourceCulture);
            }
        }
    }
}
