//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.SSIS.ControlFlow.Logging.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP.SSIS.ControlFlow.Logging.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor for {0}.
        /// </summary>
        internal static string EditorFor {
            get {
                return ResourceManager.GetString("EditorFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize property &apos;{0}&apos;. Unknown value &apos;{1}&apos;..
        /// </summary>
        internal static string ErrorCouldNotDeserializeProperty {
            get {
                return ResourceManager.GetString("ErrorCouldNotDeserializeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of variables to export is invalid.
        /// </summary>
        internal static string ErrorInvalidVariables {
            get {
                return ResourceManager.GetString("ErrorInvalidVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error locking varaibles for reading.
        /// </summary>
        internal static string ErrorLockingReadVariables {
            get {
                return ResourceManager.GetString("ErrorLockingReadVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Locking variables.
        /// </summary>
        internal static string ErrorLockingVariables {
            get {
                return ResourceManager.GetString("ErrorLockingVariables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error locking XmlVaraible &apos;{0}&apos; for writing.
        /// </summary>
        internal static string ErrorLockingXmlVariable {
            get {
                return ResourceManager.GetString("ErrorLockingXmlVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid Xml Element name.
        /// </summary>
        internal static string ErrorNotValidElementName {
            get {
                return ResourceManager.GetString("ErrorNotValidElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root element node name cannot be an empty string.
        /// </summary>
        internal static string ErrorRootXmlElementCannotBeEmpty {
            get {
                return ResourceManager.GetString("ErrorRootXmlElementCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable element name cannot be an empty string.
        /// </summary>
        internal static string ErrorVariableElementEmpty {
            get {
                return ResourceManager.GetString("ErrorVariableElementEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable has to be of type string or object.
        /// </summary>
        internal static string ErrorXmlVaraibleNotString {
            get {
                return ResourceManager.GetString("ErrorXmlVaraibleNotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable cannot be in the list of VariablesToExport.
        /// </summary>
        internal static string ErrorXmlVariableCannotBeExported {
            get {
                return ResourceManager.GetString("ErrorXmlVariableCannotBeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable cannot be evaluated as expression. It has to be user writable variable..
        /// </summary>
        internal static string ErrorXmlVariableCannotHaveExpression {
            get {
                return ResourceManager.GetString("ErrorXmlVariableCannotHaveExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable has to be specified.
        /// </summary>
        internal static string ErrorXmlVariableEmpty {
            get {
                return ResourceManager.GetString("ErrorXmlVariableEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable &apos;{0}&apos; does not exists.
        /// </summary>
        internal static string ErrorXmlVariableNotExists {
            get {
                return ResourceManager.GetString("ErrorXmlVariableNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlVariable has to be a user variable form within [User] namespace.
        /// </summary>
        internal static string ErrorXmlVariableNotUser {
            get {
                return ResourceManager.GetString("ErrorXmlVariableNotUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VariablesToXmlTask.
        /// </summary>
        internal static string VariablesToXmlTaskName {
            get {
                return ResourceManager.GetString("VariablesToXmlTaskName", resourceCulture);
            }
        }
    }
}
