//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP.SSIS.DataFlow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PP.SSIS.DataFlow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnsToXmlInput.
        /// </summary>
        internal static string ColumnsToXmlInputName {
            get {
                return ResourceManager.GetString("ColumnsToXmlInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnsToXmlOutput.
        /// </summary>
        internal static string ColumnsToXmlOutputName {
            get {
                return ResourceManager.GetString("ColumnsToXmlOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID of the source of row columns. It allows you to identify the source of the row data..
        /// </summary>
        internal static string ColumnsToXmlSourceIDDescription {
            get {
                return ResourceManager.GetString("ColumnsToXmlSourceIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceID.
        /// </summary>
        internal static string ColumnsToXmlSourceIDProperty {
            get {
                return ResourceManager.GetString("ColumnsToXmlSourceIDProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the source of row columns. It allows you to identify the source of the row data..
        /// </summary>
        internal static string ColumnsToXmlSourceNameDescription {
            get {
                return ResourceManager.GetString("ColumnsToXmlSourceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceName.
        /// </summary>
        internal static string ColumnsToXmlSourceNameProperty {
            get {
                return ResourceManager.GetString("ColumnsToXmlSourceNameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms selected input columns to XML.
        /// </summary>
        internal static string ColumnsToXMLTransformationDescription {
            get {
                return ResourceManager.GetString("ColumnsToXMLTransformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTX_ColumnsToXml.
        /// </summary>
        internal static string ColumnsToXMLTransformationName {
            get {
                return ResourceManager.GetString("ColumnsToXMLTransformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor for {0}.
        /// </summary>
        internal static string EditorFor {
            get {
                return ResourceManager.GetString("EditorFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not allows adding columns.
        /// </summary>
        internal static string ErrorAddColumn {
            get {
                return ResourceManager.GetString("ErrorAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not allow adding inputs..
        /// </summary>
        internal static string ErrorAddInput {
            get {
                return ResourceManager.GetString("ErrorAddInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not allow adding outputs..
        /// </summary>
        internal static string ErrorAddOutput {
            get {
                return ResourceManager.GetString("ErrorAddOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves ErrorColumnName and ErrorDescription for Error Columns.
        /// </summary>
        internal static string ErrorColumnMetadataTransformationDescription {
            get {
                return ResourceManager.GetString("ErrorColumnMetadataTransformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECM_ErrorColumnMetadata.
        /// </summary>
        internal static string ErrorColumnMetadataTransformationName {
            get {
                return ResourceManager.GetString("ErrorColumnMetadataTransformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not allow deleting inputs..
        /// </summary>
        internal static string ErrorDeleteInput {
            get {
                return ResourceManager.GetString("ErrorDeleteInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not allow deleting outputs..
        /// </summary>
        internal static string ErrorDeleteOutput {
            get {
                return ResourceManager.GetString("ErrorDeleteOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupCaptureNumber must be greater than or equal to 0.
        /// </summary>
        internal static string ErrorGrouCaptureNumberLowerThanZero {
            get {
                return ResourceManager.GetString("ErrorGrouCaptureNumberLowerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name &apos;{0}&apos; does not exists in Regular Expression &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorGroupNameNotExistsInRegex {
            get {
                return ResourceManager.GetString("ErrorGroupNameNotExistsInRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Number &apos;{0}&apos; does not exists in Regular Expression &apos;{1}&apos;.
        /// </summary>
        internal static string ErrorGroupNumberNotExistsInRegex {
            get {
                return ResourceManager.GetString("ErrorGroupNumberNotExistsInRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of Inputs..
        /// </summary>
        internal static string ErrorIncorrectNumberOfInputs {
            get {
                return ResourceManager.GetString("ErrorIncorrectNumberOfInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of outputs..
        /// </summary>
        internal static string ErrorIncorrectNumberOfOutputs {
            get {
                return ResourceManager.GetString("ErrorIncorrectNumberOfOutputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataType [{0}] of Input Column &apos;{1}&apos; with LineageID={2} is not supported.
        /// </summary>
        internal static string ErrorInputColumnDataTypeNotSupported {
            get {
                return ResourceManager.GetString("ErrorInputColumnDataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no InputColumn with LineageID = {0}.
        /// </summary>
        internal static string ErrorInputColumnLineageNotExists {
            get {
                return ResourceManager.GetString("ErrorInputColumnLineageNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input column &apos;{0}&apos; does not match a column in the upstream component..
        /// </summary>
        internal static string ErrorInputColumnNotInUpstreamComponent {
            get {
                return ResourceManager.GetString("ErrorInputColumnNotInUpstreamComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input column not specified.
        /// </summary>
        internal static string ErrorInputColumnNotSpecified {
            get {
                return ResourceManager.GetString("ErrorInputColumnNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input property &apos;{0}&apos; cannot be changed..
        /// </summary>
        internal static string ErrorInputColumnPropertyCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorInputColumnPropertyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Column &apos;{0}&apos; is missing SortOrder property.
        /// </summary>
        internal static string ErrorInputMissingSortOrder {
            get {
                return ResourceManager.GetString("ErrorInputMissingSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Input.
        /// </summary>
        internal static string ErrorInputName {
            get {
                return ResourceManager.GetString("ErrorInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output column &apos;{0}&apos; has wrong data type..
        /// </summary>
        internal static string ErrorInvalidDataType {
            get {
                return ResourceManager.GetString("ErrorInvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Hash Type of output column &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorInvalidHashType {
            get {
                return ResourceManager.GetString("ErrorInvalidHashType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XxmlSaveOption of output column &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorInvalidSaveOption {
            get {
                return ResourceManager.GetString("ErrorInvalidSaveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Error Input  has to be attached.
        /// </summary>
        internal static string ErrorLookupErrorAggInputNotAttached {
            get {
                return ResourceManager.GetString("ErrorLookupErrorAggInputNotAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupSourceID property of the component has to be provided.
        /// </summary>
        internal static string ErrorLookupErrorAggSourceIDNotProvided {
            get {
                return ResourceManager.GetString("ErrorLookupErrorAggSourceIDNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Aggregated Error Input is not attached to Aggregated Error Output.
        /// </summary>
        internal static string ErrorLookupErrorAggUpstreamNotAggregatedLookupError {
            get {
                return ResourceManager.GetString("ErrorLookupErrorAggUpstreamNotAggregatedLookupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Number must be grater than 0.
        /// </summary>
        internal static string ErrorMatchNumberLowerThanOne {
            get {
                return ResourceManager.GetString("ErrorMatchNumberLowerThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input for the Main Data.
        /// </summary>
        internal static string ErrorMetadataDataInputDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataDataInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Input.
        /// </summary>
        internal static string ErrorMetadataDataInputName {
            get {
                return ResourceManager.GetString("ErrorMetadataDataInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output for the main upstream data.
        /// </summary>
        internal static string ErrorMetadataDataOutputDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataDataOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Output.
        /// </summary>
        internal static string ErrorMetadataDataOutputName {
            get {
                return ResourceManager.GetString("ErrorMetadataDataOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorMetadata.
        /// </summary>
        internal static string ErrorMetadataDefaultOutputColumnName {
            get {
                return ResourceManager.GetString("ErrorMetadataDefaultOutputColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains description of the Error Code.
        /// </summary>
        internal static string ErrorMetadataErrorCodeDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataErrorCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains name of the ErrorColumn.
        /// </summary>
        internal static string ErrorMetadataErrorColumnNameDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataErrorColumnNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input for upstream Error output to get ErrorColumnName and ErrorDescription.
        /// </summary>
        internal static string ErrorMetadataErrorInputDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataErrorInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds ErrorColumnName and ErrorDescrition to the Error output.
        /// </summary>
        internal static string ErrorMetadataErrorOutputDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataErrorOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeUpstreamComponentName.
        /// </summary>
        internal static string ErrorMetadataIncludeUpstreamComponentNameName {
            get {
                return ResourceManager.GetString("ErrorMetadataIncludeUpstreamComponentNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether Upstream component name should be included in the ErrorColumnName.
        /// </summary>
        internal static string ErrorMetadataIncludeUpstremComponentNameDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataIncludeUpstremComponentNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the input column containing data for the output column.
        /// </summary>
        internal static string ErrorMetadataInputDataColumnDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataInputDataColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputDataColumn.
        /// </summary>
        internal static string ErrorMetadataInputDataColumnName {
            get {
                return ResourceManager.GetString("ErrorMetadataInputDataColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type of the coutput column. Whether it is ErrorColumnName or ErrorDescription.
        /// </summary>
        internal static string ErrorMetadataOutputColumnTypeDescription {
            get {
                return ResourceManager.GetString("ErrorMetadataOutputColumnTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutputColumnType.
        /// </summary>
        internal static string ErrorMetadataOutputColumnTypeName {
            get {
                return ResourceManager.GetString("ErrorMetadataOutputColumnTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output property &apos;{0}&apos; cannot be changed..
        /// </summary>
        internal static string ErrorOutputColumnPropertyCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorOutputColumnPropertyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Output.
        /// </summary>
        internal static string ErrorOutputName {
            get {
                return ResourceManager.GetString("ErrorOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component does not support input columns.
        /// </summary>
        internal static string ErrorRowNmberInputColumnsInvalid {
            get {
                return ResourceManager.GetString("ErrorRowNmberInputColumnsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported value. Increment can be only in days=d, weeks=w,  months=m or years=y.
        /// </summary>
        internal static string ErrorUnsupportedRowNumberIncrementValue {
            get {
                return ResourceManager.GetString("ErrorUnsupportedRowNumberIncrementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Validating Column {0}: {1}.
        /// </summary>
        internal static string ErrorValidateColumn {
            get {
                return ResourceManager.GetString("ErrorValidateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The runtive version of PP.SSIS.DataFlow if out of date. Please deploye most current version.
        /// </summary>
        internal static string ErrorWrongRuntimeVersion {
            get {
                return ResourceManager.GetString("ErrorWrongRuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract data from a column based on Regular Expression.
        /// </summary>
        internal static string GetExExtractionTransformationDescription {
            get {
                return ResourceManager.GetString("GetExExtractionTransformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashAlgorithm.
        /// </summary>
        internal static string HashAlgorithmPropertyName {
            get {
                return ResourceManager.GetString("HashAlgorithmPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Hash of selected input columns.
        /// </summary>
        internal static string HashColumnDefaultDesccription {
            get {
                return ResourceManager.GetString("HashColumnDefaultDesccription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashValue.
        /// </summary>
        internal static string HashColumnDefaultName {
            get {
                return ResourceManager.GetString("HashColumnDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains Hash of selected input columns.
        /// </summary>
        internal static string HashColumnDescription {
            get {
                return ResourceManager.GetString("HashColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashFieldSeparator.
        /// </summary>
        internal static string HashColumnHashFieldSeparatorPropertyName {
            get {
                return ResourceManager.GetString("HashColumnHashFieldSeparatorPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashImplementationType.
        /// </summary>
        internal static string HashColumnHashImplementationTypePropertyName {
            get {
                return ResourceManager.GetString("HashColumnHashImplementationTypePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashInputColumns.
        /// </summary>
        internal static string HashColumnHashInputColumnsPropertyName {
            get {
                return ResourceManager.GetString("HashColumnHashInputColumnsPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashOutputDataType.
        /// </summary>
        internal static string HashColumnHashOutputDataTypePropertyName {
            get {
                return ResourceManager.GetString("HashColumnHashOutputDataTypePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullReplacementValue.
        /// </summary>
        internal static string HashColumnNullReplacementValue {
            get {
                return ResourceManager.GetString("HashColumnNullReplacementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains columns calculating hashes of input columns.
        /// </summary>
        internal static string HashColumnOutputDescription {
            get {
                return ResourceManager.GetString("HashColumnOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashColumnsInput.
        /// </summary>
        internal static string HashColumnsInputName {
            get {
                return ResourceManager.GetString("HashColumnsInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HashColumnsOutput.
        /// </summary>
        internal static string HashColumnsOutputName {
            get {
                return ResourceManager.GetString("HashColumnsOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computes Hash of selected columns based on selected Hash algorithm..
        /// </summary>
        internal static string HashColumnsTransformationDescription {
            get {
                return ResourceManager.GetString("HashColumnsTransformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCT_HashColumns.
        /// </summary>
        internal static string HashColumnsTransformationName {
            get {
                return ResourceManager.GetString("HashColumnsTransformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StringsTrimming.
        /// </summary>
        internal static string HashColumnStringTrimmingPropertyName {
            get {
                return ResourceManager.GetString("HashColumnStringTrimmingPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParallelProcessing.
        /// </summary>
        internal static string HashTransformationParallelProcessingPropertyName {
            get {
                return ResourceManager.GetString("HashTransformationParallelProcessingPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Hash algorithm to be used.
        /// </summary>
        internal static string HashTypePropertyDescription {
            get {
                return ResourceManager.GetString("HashTypePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the Sor Order of the Input Column at which it will be processed during input processing..
        /// </summary>
        internal static string InputSortOrderPropertyDescription {
            get {
                return ResourceManager.GetString("InputSortOrderPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SortOrder.
        /// </summary>
        internal static string InputSortOrderPropertyName {
            get {
                return ResourceManager.GetString("InputSortOrderPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs aggregated error information.
        /// </summary>
        internal static string LookupErrorAggAggregatedErrorOutputDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggAggregatedErrorOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregated Error Output.
        /// </summary>
        internal static string LookupErrorAggAggregatedErrorOutputName {
            get {
                return ResourceManager.GetString("LookupErrorAggAggregatedErrorOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates the number of lookup errors on the key combination..
        /// </summary>
        internal static string LookupErrorAggCountDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string LookupErrorAggCountName {
            get {
                return ResourceManager.GetString("LookupErrorAggCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregates Looup Errors for logging purposes..
        /// </summary>
        internal static string LookupErrorAggDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides input of data to aggregate.
        /// </summary>
        internal static string LookupErrorAggErrorInputDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggErrorInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream data input.
        /// </summary>
        internal static string LookupErrorAggErrorInputName {
            get {
                return ResourceManager.GetString("LookupErrorAggErrorInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronous output for upstream data.
        /// </summary>
        internal static string LookupErrorAggErrorOutputDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggErrorOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream data output.
        /// </summary>
        internal static string LookupErrorAggErrorOutputName {
            get {
                return ResourceManager.GetString("LookupErrorAggErrorOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the InputColumn is Key Column.
        /// </summary>
        internal static string LookupErrorAggIsKeyColumnDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggIsKeyColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsKeyColumn.
        /// </summary>
        internal static string LookupErrorAggIsKeyColumnName {
            get {
                return ResourceManager.GetString("LookupErrorAggIsKeyColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether Input Column is Null Detection Column.
        /// </summary>
        internal static string LookupErrorAggIsNullColumnDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggIsNullColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNullColumn.
        /// </summary>
        internal static string LookupErrorAggIsNullColumnName {
            get {
                return ResourceManager.GetString("LookupErrorAggIsNullColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counts total number of unique Key Combinations.
        /// </summary>
        internal static string LookupErrorAggKeysCountDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggKeysCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeysCount.
        /// </summary>
        internal static string LookupErrorAggKeysCountName {
            get {
                return ResourceManager.GetString("LookupErrorAggKeysCountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides information about the lookup key columns in XML Format.
        /// </summary>
        internal static string LookupErrorAggLookpDetaislXmlDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggLookpDetaislXmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupDetailsXml.
        /// </summary>
        internal static string LookupErrorAggLookpDetaislXmlName {
            get {
                return ResourceManager.GetString("LookupErrorAggLookpDetaislXmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the Lookup source.
        /// </summary>
        internal static string LookupErrorAggLookupSourceDescriptionDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggLookupSourceDescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupSourceDescription.
        /// </summary>
        internal static string LookupErrorAggLookupSourceDescriptionName {
            get {
                return ResourceManager.GetString("LookupErrorAggLookupSourceDescriptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification of the Lookup source.
        /// </summary>
        internal static string LookupErrorAggLookupSourceIDDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggLookupSourceIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupSourceID.
        /// </summary>
        internal static string LookupErrorAggLookupSourceIDName {
            get {
                return ResourceManager.GetString("LookupErrorAggLookupSourceIDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEA_LookupErrorAggregation.
        /// </summary>
        internal static string LookupErrorAggName {
            get {
                return ResourceManager.GetString("LookupErrorAggName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process only when selected column is null. Used to detect lookup errors when Ignore is selected in the Lookup Component..
        /// </summary>
        internal static string LookupErrorAggNullColumnDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggNullColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullColumn.
        /// </summary>
        internal static string LookupErrorAggNullColumnName {
            get {
                return ResourceManager.GetString("LookupErrorAggNullColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Aggreagated Error Output of previous LookupErrorAggregation, which llows easy Unioning of Upstream Aggregated errors..
        /// </summary>
        internal static string LookupErrorAggUpstreamErrorInputDescription {
            get {
                return ResourceManager.GetString("LookupErrorAggUpstreamErrorInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upstream Aggregated Error Input.
        /// </summary>
        internal static string LookupErrorAggUpstreamErrorInputNamme {
            get {
                return ResourceManager.GetString("LookupErrorAggUpstreamErrorInputNamme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx.
        /// </summary>
        internal static string RegExExpressionDefaultOutputColumnName {
            get {
                return ResourceManager.GetString("RegExExpressionDefaultOutputColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the Capture of the CaptureGroup to return in there are more captures of that group. Default 0 means last capture..
        /// </summary>
        internal static string RegExExtractionGroupCaptureNumberPropertyDescription {
            get {
                return ResourceManager.GetString("RegExExtractionGroupCaptureNumberPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupCaptureNumber.
        /// </summary>
        internal static string RegExExtractionGroupCaptureNumberPropertyName {
            get {
                return ResourceManager.GetString("RegExExtractionGroupCaptureNumberPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of the Regular Expression Group to return as the output column.
        /// </summary>
        internal static string RegExExtractionGroupDescription {
            get {
                return ResourceManager.GetString("RegExExtractionGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Regular Expression Group to which the Output column is Mapped.
        /// </summary>
        internal static string RegExExtractionGroupNamePropertyDescription {
            get {
                return ResourceManager.GetString("RegExExtractionGroupNamePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupName.
        /// </summary>
        internal static string RegExExtractionGroupNamePropertyName {
            get {
                return ResourceManager.GetString("RegExExtractionGroupNamePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the Regular Expression Group to which the Output Column is Mapped.
        /// </summary>
        internal static string RegExExtractionGroupNumberPropertyDescription {
            get {
                return ResourceManager.GetString("RegExExtractionGroupNumberPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupNumber.
        /// </summary>
        internal static string RegExExtractionGroupNumberPropertyName {
            get {
                return ResourceManager.GetString("RegExExtractionGroupNumberPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lineage ID of the Input column to which th OutputColumn is mapped.
        /// </summary>
        internal static string RegExExtractionInputColumnLinageIdPropertyDescription {
            get {
                return ResourceManager.GetString("RegExExtractionInputColumnLinageIdPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputColumnLineageID.
        /// </summary>
        internal static string RegExExtractionInputColumnLinageIdPropertyName {
            get {
                return ResourceManager.GetString("RegExExtractionInputColumnLinageIdPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputColumnName.
        /// </summary>
        internal static string RegExExtractionInputDataColumnDescription {
            get {
                return ResourceManager.GetString("RegExExtractionInputDataColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the input column containing data for the output column.
        /// </summary>
        internal static string RegExExtractionInputDataColumnName {
            get {
                return ResourceManager.GetString("RegExExtractionInputDataColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input for the Regular Expression Extraction transformation.
        /// </summary>
        internal static string RegExExtractionInputDescription {
            get {
                return ResourceManager.GetString("RegExExtractionInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegExInput.
        /// </summary>
        internal static string RegExExtractionInputName {
            get {
                return ResourceManager.GetString("RegExExtractionInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of the match the OutputColumn should return.
        /// </summary>
        internal static string RegExExtractionMatchNumberPropertyDescription {
            get {
                return ResourceManager.GetString("RegExExtractionMatchNumberPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchNumber.
        /// </summary>
        internal static string RegExExtractionMatchNumberPropertyName {
            get {
                return ResourceManager.GetString("RegExExtractionMatchNumberPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of the Regular Expression Extraction transformation.
        /// </summary>
        internal static string RegExExtractionOutputDescription {
            get {
                return ResourceManager.GetString("RegExExtractionOutputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegExOutput.
        /// </summary>
        internal static string RegExExtractionOutputName {
            get {
                return ResourceManager.GetString("RegExExtractionOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegexOptions.
        /// </summary>
        internal static string RegExExtractionRegexOptions {
            get {
                return ResourceManager.GetString("RegExExtractionRegexOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegexOutput.
        /// </summary>
        internal static string RegExExtractionRegexOutput {
            get {
                return ResourceManager.GetString("RegExExtractionRegexOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegexOutputType.
        /// </summary>
        internal static string RegExExtractionRegexOutputType {
            get {
                return ResourceManager.GetString("RegExExtractionRegexOutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies regular expression to be applied on the input column.
        /// </summary>
        internal static string RegExExtractionRegularExpressionDescription {
            get {
                return ResourceManager.GetString("RegExExtractionRegularExpressionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegularExpression.
        /// </summary>
        internal static string RegExExtractionRegularExpressionName {
            get {
                return ResourceManager.GetString("RegExExtractionRegularExpressionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REE_RegExExtraction.
        /// </summary>
        internal static string RegExExtractionTransformationName {
            get {
                return ResourceManager.GetString("RegExExtractionTransformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculates Row Number based on selected properties.
        /// </summary>
        internal static string RowNumberDefaultColumnDescription {
            get {
                return ResourceManager.GetString("RowNumberDefaultColumnDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumber.
        /// </summary>
        internal static string RowNumberDefaultColumnName {
            get {
                return ResourceManager.GetString("RowNumberDefaultColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the increment for teh Row Number.
        /// </summary>
        internal static string RowNumberIncrementByPropertyDescription {
            get {
                return ResourceManager.GetString("RowNumberIncrementByPropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncrementBy.
        /// </summary>
        internal static string RowNumberIncrementByPropertyName {
            get {
                return ResourceManager.GetString("RowNumberIncrementByPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies Initial Value of the RowNumber.
        /// </summary>
        internal static string RowNumberInitialValuePropertyDescription {
            get {
                return ResourceManager.GetString("RowNumberInitialValuePropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialValue.
        /// </summary>
        internal static string RowNumberInitialValuePropertyName {
            get {
                return ResourceManager.GetString("RowNumberInitialValuePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumberInput.
        /// </summary>
        internal static string RowNumberInputName {
            get {
                return ResourceManager.GetString("RowNumberInputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowNumberOutput.
        /// </summary>
        internal static string RowNumberOutputName {
            get {
                return ResourceManager.GetString("RowNumberOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generates Row Numbers based on DataType and Increment.
        /// </summary>
        internal static string RowNumberTranformationDescription {
            get {
                return ResourceManager.GetString("RowNumberTranformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RNT_RowNumber.
        /// </summary>
        internal static string RowNumberTransformationName {
            get {
                return ResourceManager.GetString("RowNumberTransformationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c) Pavel Pawlowski.
        /// </summary>
        internal static string TransformationContactInfo {
            get {
                return ResourceManager.GetString("TransformationContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains XML representing selected input columns.
        /// </summary>
        internal static string XmlColumnDefaultDesccription {
            get {
                return ResourceManager.GetString("XmlColumnDefaultDesccription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnsXMLData.
        /// </summary>
        internal static string XmlColumnDefaultName {
            get {
                return ResourceManager.GetString("XmlColumnDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlInputColumns.
        /// </summary>
        internal static string XmlInputColumnsPropertyname {
            get {
                return ResourceManager.GetString("XmlInputColumnsPropertyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlSaveOptions.
        /// </summary>
        internal static string XmlSaveOptionPropertyName {
            get {
                return ResourceManager.GetString("XmlSaveOptionPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies Serialization option for the XML.
        /// </summary>
        internal static string XmlSaveOptionsDescriptions {
            get {
                return ResourceManager.GetString("XmlSaveOptionsDescriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializeDataType.
        /// </summary>
        internal static string XmlSerializeDataTypeName {
            get {
                return ResourceManager.GetString("XmlSerializeDataTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether columns ID and Lineage information should be serialized..
        /// </summary>
        internal static string XmlSerializeLineageDescription {
            get {
                return ResourceManager.GetString("XmlSerializeLineageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerializeLineage.
        /// </summary>
        internal static string XmlSerializeLineageName {
            get {
                return ResourceManager.GetString("XmlSerializeLineageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceID.
        /// </summary>
        internal static string XmlSourceIdPropertyName {
            get {
                return ResourceManager.GetString("XmlSourceIdPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceName.
        /// </summary>
        internal static string XmlSourceNamePropertyName {
            get {
                return ResourceManager.GetString("XmlSourceNamePropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether data type information should be serialized..
        /// </summary>
        internal static string XmlStoreDataTypeDescription {
            get {
                return ResourceManager.GetString("XmlStoreDataTypeDescription", resourceCulture);
            }
        }
    }
}
